# Generated by Django 4.1.4 on 2022-12-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(choices=[('plano diretor norte', 'Planto diretor norte'), ('plano diretor sul', 'Plano diretor sul'), ('taquaralto', 'Taquaralto')], max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(choices=[('palmas', 'Palmas'), ('paraiso', 'Paraiso'), ('araguaina', 'Araguaina')], max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pais',
            field=models.CharField(choices=[('brasil', 'Brasil')], max_length=100),
        ),
    ]
