# Generated by Django 4.1.3 on 2022-11-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pet_cor_consultapet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nascimento', models.DateField()),
                ('cargo', models.IntegerField(choices=[(1, 'Veterinario'), (2, 'Financeiro'), (3, 'Atendimento')])),
            ],
        ),
    ]
