# Generated by Django 4.1.2 on 2022-11-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='professiao',
            new_name='profissao',
        ),
    ]
